# Generated by Django 5.1.2 on 2024-11-28 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_shop', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='cart',
            table='Cart',
        ),
        migrations.AlterModelTable(
            name='cartitems',
            table='CartItem',
        ),
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
        migrations.AlterModelTable(
            name='order',
            table='Order',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='OrderItem',
        ),
        migrations.AlterModelTable(
            name='product',
            table='Product',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='Profile',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
