# Generated by Django 5.1.2 on 2024-11-28 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_shop', '0004_alter_category_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productimage',
            table='ProductImage',
        ),
    ]
