# Generated by Django 5.1.2 on 2024-12-01 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_shop', '0004_remove_product_image_alter_product_is_available_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productimage',
            table='ProductImage',
        ),
    ]
