# Generated by Django 5.1.2 on 2024-12-01 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_shop', '0005_alter_productimage_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='Product',
        ),
    ]
