# Generated by Django 5.1.2 on 2024-12-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_shop', '0007_alter_cartitems_options_alter_subcategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='img/product_images/'),
        ),
    ]
